pipeline {
    agent any
    environment {
        APP_NAME = 'cpp_app_template'
        TEST_DOCKER_TAG_LATEST = "${APP_NAME}:test-latest"
    }
    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Build test docker') {
            steps {
                // --no-cache
                sh 'docker build -t ${TEST_DOCKER_TAG_LATEST} -f ci/dockerfile.alpine .'
            }
        }
        stage('Build and Test') {
            parallel {
                stage('Debug') {
                    agent {
                        docker {
                            image "${TEST_DOCKER_TAG_LATEST}"
                            reuseNode true
                        }
                    }
                    steps {
                        sh '/usr/bin/lua5.4 ci/ci_run.lua all-debug'
                    }
                }
                stage('Release') {
                    agent {
                        docker {
                            image "${TEST_DOCKER_TAG_LATEST}"
                            reuseNode true
                        }
                    }
                    steps {
                        sh '/usr/bin/lua5.4 ci/ci_run.lua all-release'
                    }
                }
            }
        }
        stage('Archive artifacts') {
            steps {
                archiveArtifacts artifacts: '**/Artifacts/*', followSymlinks: false
                xunit checksName: '', thresholds: [failed(unstableThreshold: '0')], tools: [GoogleTest(excludesPattern: '', pattern: 'build/**/Testing/**.xml', stopProcessingIfError: true)]
            }
        }
    }
}
