pipeline {
    agent any
    environment {
        APP_NAME = 'cpp_app_template'
        TEST_DOCKER_TAG_LATEST = "${APP_NAME}:test-latest"
    }
    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Build test docker') {
            steps {
                sh 'docker build -t ${TEST_DOCKER_TAG_LATEST} -f ci/dockerfile.alpine .'
            }
        }
        stage('Test') {
            parallel {
                stage('Debug') {
                    agent {
                        docker {
                            image "${TEST_DOCKER_TAG_LATEST}"
                            reuseNode true
                        }
                    }
                    steps {
                        sh '/bin/bash ci/ci_run.sh configure-debug'
                        sh '/bin/bash ci/ci_run.sh build-debug'
                        sh '/bin/bash ci/ci_run.sh test-debug'
                    }
                }
                stage('Release') {
                    agent {
                        docker {
                            image "${TEST_DOCKER_TAG_LATEST}"
                            reuseNode true
                        }
                    }
                    steps {
                        sh '/bin/bash ci/ci_run.sh configure-rel'
                        sh '/bin/bash ci/ci_run.sh build-rel'
                        sh '/bin/bash ci/ci_run.sh test-rel'
                    }
                }
            }
        }
    }
}
