SET(CPACK_VERBATIM_VARIABLES TRUE)
SET(CPACK_GENERATOR ZIP)

if (NOT DEFINED CMAKE_BUILD_TYPE)
    SET(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}")
else()
    SET(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}-${CMAKE_BUILD_TYPE}")
endif()

set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/Artifacts")

include(CPack)
