find_program(CLANG_TIDY_EXECUTABLE NAMES clang-tidy)

if(NOT CLANG_TIDY_EXECUTABLE)
    if(APP_DO_CLANG_TIDY)
        message(FATAL_ERROR "Clang-tidy enabled but executable is not found")
    else()
        message(STATUS "Disabling clang-tidy")
        set(CMAKE_CXX_CLANG_TIDY "")
    endif()
else()
    if(APP_DO_CLANG_TIDY)
        message(STATUS "Using clang-tidy ${CLANG_TIDY_EXECUTABLE}")
        set(CMAKE_CXX_CLANG_TIDY ${CLANG_TIDY_EXECUTABLE} --header-filter=${CMAKE_CURRENT_SOURCE_DIR}/.*)
        if (APP_CLANG_TIDY_WARNINGS_AS_ERRORS)
            set(CMAKE_CXX_CLANG_TIDY ${CMAKE_CXX_CLANG_TIDY} --warnings-as-errors=*)
        endif()
    else()
        message(STATUS "Clang-tidy found, but usage was not request. Disabling.")
    endif()
endif()

function(setup_clang_tidy TARGET_NAME)
    if(APP_DO_CLANG_TIDY)
        set_target_properties(${TARGET_NAME} PROPERTIES CXX_CLANG_TIDY "${CMAKE_CXX_CLANG_TIDY}")
    endif()
endfunction()
